### PR TITLE
Fix spelling mistake

### PR DESCRIPTION
**Pull request by supern64**

### CODE REVIEW

**Comment by Tarnadas** [comment]
Pleased rebase origin/develop once to fix CI

**Comment by chanonlim** [comment]
Clone the forked repo and do `git rebase origin/develop` right? (sorry I haven't used this)

**Comment by chanonlim** [comment]
I think I rebased it but the build still failed 🤔   
Travis says build & deploy succeeded but test failed  
Here's the test log...  
[Test log image](https://i.imgur.com/EyMfOBG.png)

**Comment by Tarnadas** [comment]
Hey, sorry for forgetting about this.
I've never seen a merge-base command, also you don't have to do an interactive rebase on a specific commitId. Instead a simple `git rebase net64-mod/develop && git push -f` would have been enough after adding the remote.
There are many ways to fix your git branch, but it would be probably easiest to just recreate your branch from scratch.

**Comment by chanonlim** [comment]
OK, I'll look into it later

On Thu, Mar 14, 2019, 12:51 Mario Reder <notifications@github.com<mailto:notifications@github.com>> wrote:

Hey, sorry for forgetting about this.
I've never seen a merge-base command, also you don't have to do an interactive rebase on a specific commitId. Instead a simple git rebase net64-mod/develop && git push -f would have been enough after adding the remote.
There are many ways to fix your git branch, but it would be probably easiest to just recreate your branch from scratch.

**Pull request closed without merging**
